# Generated by Django 2.2 on 2020-04-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ls_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ls_staff',
            new_name='is_staff',
        ),
    ]
